from pathlib import Path

from services.architecture_contract import contract_for_stack, write_contract
from services.file_writer import resolve_output_dir, safe_project_path
from services.system_blueprint import ensure_blueprint


PROJECT_TEMPLATES = {
    "auto": {
        "name": "Auto Select",
        "description": "Let the Manager choose the best structure from the goal.",
        "files": {},
    },
    "fastapi": {
        "name": "Python FastAPI API",
        "description": "Backend API with FastAPI, SQLite-ready structure, and pytest.",
        "files": {
            "README.md": "# {project_name}\n\nFastAPI backend generated by Wacko Inc OS.\n",
            "requirements.txt": "fastapi\nuvicorn\nsqlalchemy\npydantic\npython-dotenv\npytest\n",
            ".env.example": "DATABASE_URL=sqlite:///app.db\n",
            "app/main.py": (
                "from fastapi import FastAPI\n\n"
                "app = FastAPI(title=\"{project_name}\")\n\n\n"
                "@app.get(\"/health\")\n"
                "def health():\n"
                "    return {\"status\": \"ok\"}\n"
            ),
            "app/__init__.py": "",
            "tests/test_health.py": (
                "from app.main import health\n\n\n"
                "def test_health():\n"
                "    assert health() == {\"status\": \"ok\"}\n"
            ),
        },
    },
    "vue": {
        "name": "Vue 3 App",
        "description": "Vue/Vite frontend skeleton ready for Vuetify or PrimeVue.",
        "files": {
            "README.md": "# {project_name}\n\nVue frontend generated by Wacko Inc OS.\n",
            "package.json": (
                "{\n"
                "  \"scripts\": {\"dev\": \"vite\", \"build\": \"vite build\", \"preview\": \"vite preview\"},\n"
                "  \"dependencies\": {\"@vitejs/plugin-vue\": \"latest\", \"vite\": \"latest\", \"vue\": \"latest\"},\n"
                "  \"devDependencies\": {}\n"
                "}\n"
            ),
            "index.html": "<div id=\"app\"></div><script type=\"module\" src=\"/src/main.js\"></script>\n",
            "src/main.js": (
                "import { createApp } from 'vue'\n"
                "import App from './App.vue'\n"
                "import './styles.css'\n\n"
                "createApp(App).mount('#app')\n"
            ),
            "src/App.vue": (
                "<template>\n"
                "  <main class=\"app-shell\">\n"
                "    <h1>{project_name}</h1>\n"
                "  </main>\n"
                "</template>\n"
            ),
            "src/styles.css": "body { margin: 0; font-family: Segoe UI, Arial, sans-serif; }\n",
        },
    },
    "fastapi-vue": {
        "name": "FastAPI + Vue",
        "description": "Full-stack app with FastAPI backend and Vue frontend folders.",
        "files": {
            "README.md": "# {project_name}\n\nFull-stack FastAPI + Vue project generated by Wacko Inc OS.\n",
            "backend/requirements.txt": "fastapi\nuvicorn\nsqlalchemy\npydantic\npython-dotenv\npytest\n",
            "backend/app/main.py": (
                "from fastapi import FastAPI\n"
                "from fastapi.middleware.cors import CORSMiddleware\n\n"
                "app = FastAPI(title=\"{project_name} API\")\n"
                "app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_methods=[\"*\"], allow_headers=[\"*\"])\n\n\n"
                "@app.get(\"/health\")\n"
                "def health():\n"
                "    return {\"status\": \"ok\"}\n"
            ),
            "backend/app/__init__.py": "",
            "backend/tests/test_health.py": (
                "from app.main import health\n\n\n"
                "def test_health():\n"
                "    assert health() == {\"status\": \"ok\"}\n"
            ),
            "frontend/package.json": (
                "{\n"
                "  \"scripts\": {\"dev\": \"vite\", \"build\": \"vite build\", \"preview\": \"vite preview\"},\n"
                "  \"dependencies\": {\"@vitejs/plugin-vue\": \"latest\", \"vite\": \"latest\", \"vue\": \"latest\"},\n"
                "  \"devDependencies\": {}\n"
                "}\n"
            ),
            "frontend/index.html": "<div id=\"app\"></div><script type=\"module\" src=\"/src/main.js\"></script>\n",
            "frontend/src/main.js": "import { createApp } from 'vue'\nimport App from './App.vue'\n\ncreateApp(App).mount('#app')\n",
            "frontend/src/App.vue": "<template><main><h1>{project_name}</h1></main></template>\n",
        },
    },
    "dotnet-api": {
        "name": ".NET 8 Web API",
        "description": "ASP.NET Core style API skeleton.",
        "files": {
            "README.md": "# {project_name}\n\n.NET API project generated by Wacko Inc OS.\n",
            "src/Program.cs": (
                "var builder = WebApplication.CreateBuilder(args);\n"
                "builder.Services.AddEndpointsApiExplorer();\n"
                "var app = builder.Build();\n"
                "app.MapGet(\"/health\", () => Results.Ok(new { status = \"ok\" }));\n"
                "app.Run();\n"
            ),
            "src/appsettings.json": "{\n  \"Logging\": {\"LogLevel\": {\"Default\": \"Information\"}}\n}\n",
        },
    },
}


def list_templates() -> dict:
    return {
        key: {"name": value["name"], "description": value["description"]}
        for key, value in PROJECT_TEMPLATES.items()
    }


def template_for(stack: str | None) -> tuple[str, dict]:
    key = (stack or "auto").strip().lower()
    if key not in PROJECT_TEMPLATES:
        key = "auto"
    return key, PROJECT_TEMPLATES[key]


def choose_template_from_goal(goal: str, stack: str | None) -> str:
    key, _ = template_for(stack)
    if key != "auto":
        return key

    lowered = goal.lower()
    if "vue" in lowered or "frontend" in lowered:
        if "api" in lowered or "backend" in lowered or "full" in lowered:
            return "fastapi-vue"
        return "vue"
    if ".net" in lowered or "asp.net" in lowered or "c#" in lowered:
        return "dotnet-api"
    if "api" in lowered or "backend" in lowered or "ticket" in lowered or "helpdesk" in lowered:
        return "fastapi"
    return "fastapi-vue"


def seed_project_template(project_name: str, goal: str, stack: str | None, output_dir: str | None = None) -> dict:
    selected_stack = choose_template_from_goal(goal, stack)
    _, template = template_for(selected_stack)
    project_dir = resolve_output_dir(project_name, output_dir)
    project_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for relative_path, content in template["files"].items():
        file_path = safe_project_path(project_dir, relative_path)
        file_path.parent.mkdir(parents=True, exist_ok=True)
        if file_path.exists():
            continue
        file_path.write_text(content.replace("{project_name}", project_name), encoding="utf-8")
        written.append(str(file_path))

    contract = contract_for_stack(project_name, selected_stack, goal)
    contract_result = write_contract(str(project_dir), contract)
    blueprint_result = ensure_blueprint(str(project_dir), project_name, goal, selected_stack)

    return {
        "stack": selected_stack,
        "template_name": template["name"],
        "project_dir": str(project_dir),
        "seed_files": written,
        "architecture": contract_result,
        "blueprint": blueprint_result,
    }
